### ISSUE TITLE
Syntax error on AMD Ryzen 9 3900XT 12 Core 24 Thread CPU on Linux Mint 20

### ISSUE THREAD

**Issue by GoldJohnKing** [erayymz/Ortho4XPImageChecker#4]
Full console output here, see the bottom error pops up.

```
------------------------------------------------------------------------------------------------------------------------
I have determined there are 24 available logical cores.
Do you wish to use all available cores for maximum performance? (yes/no)no

I will run at 1/3rd capacity. Using only 8 logical cores out of total 24
This will be slower however other applications can be run without perfoirmance degradation.
------------------------------------------------------------------------------------------------------------------------

Do you wish to DELETE corrupt jpg files automatically? (yes/no)yes

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Any jpg files containing white space will be deleted without confirmation!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

------------------------------------------------------------------------------------------------------------------------
There are 36 image files to check.
This operation will take approximately less than one minute(s).
Starting in five seconds >>>>>
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12320_26976_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12320_26944_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12336_26944_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12336_27024_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12352_26944_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12352_26992_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12368_26944_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12368_26976_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12368_26992_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12368_26960_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12320_26960_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12352_26960_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12336_26928_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12352_27008_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12352_26928_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12336_27008_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12384_26928_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12384_26960_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12400_26944_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_16/24752_54000_GO216.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_16/24784_53920_GO216.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_16/24800_53904_GO216.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_17/49536_107936_GO217.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_17/49600_107872_GO217.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_18/99072_215936_GO218.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_18/99200_215680_GO218.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12384_26944_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_15/12384_26976_GO215.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_16/24784_53904_GO216.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_16/24784_53936_GO216.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_16/24800_53952_GO216.jpg
PROCESSING IMAGE: /media/gjk/C14D581BDA18EBFA/Ortho4XP/Orthophotos/+40+110/+40+116/GO2_18/99136_215936_GO218.jpg
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "O4XP_Image_Checker.py", line 51, in work
    if has_white_rects(str(path)):
  File "O4XP_Image_Checker.py", line 20, in has_white_rects
    r1s, r1e = last_rows[i-2]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "O4XP_Image_Checker.py", line 141, in <module>
    main()
  File "O4XP_Image_Checker.py", line 127, in main
    p.map(partial(work, delete_file=delete_file), image_files)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range
```

**Comment by GoldJohnKing** [comment]
No reply since post, close.
